name: Push M3U File Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a la medianoche UTC
  workflow_dispatch:  # Permite que se ejecute manualmente si es necesario

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}  # Usamos el token de acceso personal

    - name: Descargar archivo M3U
      run: |
        curl -o lista-ott.m3u https://proxy.zeronet.dev/1JKe3VPvFe35bm1aiHdD4p1xcGCkZKhH3Q/data/listas/lista_iptv.m3u
        curl -o lista-ott-ac.m3u https://proxy.zeronet.dev/1JKe3VPvFe35bm1aiHdD4p1xcGCkZKhH3Q/data/listas/lista_fuera_iptv.m3u

    - name: Configurar Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Hacer commit y push del archivo M3U
      run: |
        git add lista-ott.m3u lista-ott-ac.m3u
        git commit -m "Actualización diaria del archivo M3U"
        git push
