name: Push M3U File Daily

on:
  schedule:
    - cron: '0 0 * * *'          # Todos los días a las 00 UTC
  workflow_dispatch:

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar el repo
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # 2) Arrancar ZeroNet en segundo plano
      - name: Iniciar ZeroNet
        run: |
          docker run -d --name zeronet \
            -p 43110:43110 \
            nofish/zeronet \
            ./ZeroNet.sh --ui_ip 0.0.0.0 --ui_port 43110 --ui_host 127.0.0.1  # escucha fuera del contenedor :contentReference[oaicite:1]{index=1}

      # 3) Esperar a que la UI responda (máx 4 min)
      - name: Esperar a ZeroNet
        shell: bash
        run: |
          for i in {1..24}; do
            if curl -fs http://127.0.0.1:43110/ >/dev/null 2>&1; then
              echo "ZeroNet listo ✔"
              exit 0
            fi
            echo "ZeroNet aún no responde… reintento en 10 s"
            sleep 10
          done
          echo "Timeout: ZeroNet nunca respondió" >&2
          docker logs zeronet || true
          exit 1

      # 4) Descargar la lista y sobrescribir lista-ott.m3u
      - name: Descargar lista M3U
        run: |
          curl -Ls -o lista-ott.m3u \
            http://127.0.0.1:43110/1H3KoazXt2gCJgeD8673eFvQYXG7cbRddU/lista-ott.m3u

      # 5) Configurar Git
      - name: Configurar Git
        run: |
          git config --global user.name  "github-actions"
          git config --global user.email "github-actions@github.com"

      # 6) Commit & push sólo si cambió el archivo
      - name: Commit y push si hay cambios
        run: |
          git add lista-ott.m3u
          if git diff --cached --quiet; then
            echo "Sin cambios, no se hace commit."
          else
            git commit -m "Actualización diaria de lista-ott.m3u desde ZeroNet"
            git push
          fi

      # 7) Parar y limpiar el contenedor
      - name: Limpiar ZeroNet
        if: always()
        run: |
          docker stop zeronet
          docker rm   zeronet
