name: Update lista-ott.m3u

on:
  workflow_dispatch: # Solo activación manual

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl

      - name: Install ZeroNet
        run: |
          wget https://github.com/HelloZeroNet/ZeroNet-linux/archive/dist-linux64/ZeroNet-py3-linux64.tar.gz
          tar xvpfz ZeroNet-py3-linux64.tar.gz
          mv ZeroNet-linux-dist-linux64 ZeroNet
          cd ZeroNet
          ./ZeroNet.sh --version

      - name: Start ZeroNet and download file
        run: |
          nohup ./ZeroNet/ZeroNet.sh &

          # Comprobar si ZeroNet está en línea antes de continuar
          until curl -s "http://127.0.0.1:43110/" > /dev/null; do
            echo "Esperando a que ZeroNet esté en línea..."
            sleep 10  # Esperar 10 segundos antes de intentarlo de nuevo
          done

          echo "ZeroNet está en línea, procediendo con la descarga del archivo."

          curl http://127.0.0.1:43110/1H3KoazXt2gCJgeD8673eFvQYXG7cbRddU/lista-ott.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add lista-ott.m3u
          git commit -m "Actualizar lista-ott.m3u"
          git push
