name: Update lista-ott.m3u

on:
  workflow_dispatch: # Solo activación manual

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl

      - name: Install ZeroNet
        run: |
          wget https://github.com/HelloZeroNet/ZeroNet-linux/archive/dist-linux64/ZeroNet-py3-linux64.tar.gz
          tar xvpfz ZeroNet-py3-linux64.tar.gz
          mv ZeroNet-linux-dist-linux64 ZeroNet
          cd ZeroNet
          ./ZeroNet.sh --version

      - name: Start ZeroNet and download file
        run: |
          nohup ./ZeroNet/ZeroNet.sh &
          sleep 120 # Aumentar el tiempo de espera para asegurar que ZeroNet esté listo
          
          # Forzar la descarga del sitio en ZeroNet
          curl "http://127.0.0.1:43110/1H3KoazXt2gCJgeD8673eFvQYXG7cbRddU/" -m 60 || {
            echo "Error: No se pudo cargar el sitio en ZeroNet";
            exit 1;
          }
          
          # Verificar si el archivo está disponible antes de descargarlo
          content_type=$(curl -sI http://127.0.0.1:43110/1H3KoazXt2gCJgeD8673eFvQYXG7cbRddU/lista-ott.m3u | grep -i "Content-Type")
          if [[ "$content_type" != *"audio/x-mpegurl"* && "$content_type" != *"application/octet-stream"* ]]; then
            echo "Error: El archivo descargado no es un M3U válido";
            exit 1;
          fi
          
          wget -O lista-ott.m3u.tmp http://127.0.0.1:43110/1H3KoazXt2gCJgeD8673eFvQYXG7cbRddU/lista-ott.m3u || {
            echo "Error: No se pudo descargar lista-ott.m3u";
            exit 1;
          }
          
          mv lista-ott.m3u.tmp lista-ott.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add lista-ott.m3u
          git commit -m "Actualizar lista-ott.m3u"
          git push