name: Push M3U File Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  push-file:
    runs-on: ubuntu-latest

    services:
      zeronet:
        image: nofish/zeronet
        ports:
          - 43110:43110      # UI de ZeroNet

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    # Esperamos hasta 4 min o salimos
    - name: Esperar a ZeroNet
      shell: bash
      run: |
        for i in {1..24}; do
          if curl -fs http://127.0.0.1:43110/ >/dev/null 2>&1; then
            echo "ZeroNet listo ✔"
            exit 0
          fi
          echo "ZeroNet aún no responde, reintentando en 10 s…"
          sleep 10
        done
        echo "Timeout: ZeroNet nunca respondió" >&2
        exit 1

    - name: Descargar listas M3U
      run: |
        set -e
        curl -Ls -o lista-ott.m3u https://proxy.zeronet.dev/1JKe3VPvFe35bm1aiHdD4p1xcGCkZKhH3Q/data/listas/lista_iptv.m3u
        curl -Ls -o lista-ott-ac.m3u https://proxy.zeronet.dev/1JKe3VPvFe35bm1aiHdD4p1xcGCkZKhH3Q/data/listas/lista_fuera_iptv.m3u
        curl -Ls -o lista-ott-zn.m3u http://127.0.0.1:43110/1H3KoazXt2gCJgeD8673eFvQYXG7cbRddU/lista-ott.m3u

    - name: Configurar Git
      run: |
        git config --global user.name  "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Commit y push si hay cambios
      run: |
        git add lista-ott*.m3u
        git diff --cached --quiet || {
          git commit -m "Actualización diaria de listas M3U (incluye ZeroNet)"
          git push
        }
